####################################################
# Welcome to Doxy Jekyll Template
# Product Link : https://themeix.com/product/doxy-documentation-website-jekyll-template/
# Version : v3.0.0
####################################################

# Site settings
title: "Allpremiums promotionele producten"
email: buddy@allpremiums.nl
tel: "+31 (0) 252 - 235 253"
tel-link: "+31252235253"
description: "Allpremiums - voor de leukste promotie artikelen om reclame mee te maken"
keywords: "premiums, give aways, promotieartikelen, promotionele producten, promotiemiddelen en weggevertjes"
baseurl: ""
url: "https://dev.allpremiums.nl"
robots: NOINDEX,NOFOLLOW
cover_image: "/assets/images/allpremiums-preview.png"

logo: /assets/images/allpremiums-logo.svg
logo-png: /assets/images/allpremiums-logo.png
logo1280-png: /assets/images/allpremiums-logo-1280.png

# Google Analytics
#analytics_id: UA-3767152-1

# Build settings
sass:
    style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-extract-element
  - jekyll-seo-tag
  - jekyll-webp
  - jekyll-redirect-from

collections:
  producten:
    output: true
    permalink: /:collection/:title/

###################################################################
# Site configuration for the Jekyll 2 Pagination Gem
###################################################################
pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 10
  #permalink: '/pages/:num/' # Pages are simple html files
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after:
  extension: 'html'
  indexpage: 'index'

autopages:
  enabled: true
  collections:
    layouts:
      - 'tag_page.html'
    title: ' :coll' # :coll is replaced by the collection name
    permalink: '/:coll/'

  tags:
    layouts:
      - 'tag_page.html'
    title: ':tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'


# Tag Options
tag_page_layout: tag_page
tag_page_dir: tag
permalink: /:title/

#feed:
#  collections:
#    posts:
#      path: "/index.xml"

webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  gifs: [".gif"]
  regenerate: false
  webp_path: nil
  exclude: []
  append_ext: false
